#! /usr/bin/env bash
set -e
umask 0002

DESTDIR=../www
PELICAN=../venv/bin/pelican
test -x "$PELICAN" || exit
echo "Publishing changes from master"

TEMPDIR=$(mktemp -d ../tmpXXXXX)
trap "rm -rf $TEMPDIR" EXIT
git archive master | ( cd "$TEMPDIR"; tar x )
cd $TEMPDIR
"$PELICAN" content -o "$DESTDIR"
/sbin/restorecon -r "$DESTDIR"
echo "Done"
